### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/eu.scarpetta.PDFMixTool#1] opened 2018-07-01 17:34 UTC
I doesn't matter which PDF files I try to merge, it always crashes with this error:

```
terminate called after throwing an instance of 'PoDoFo::PdfError'

Thread 1 "pdfmixtool" received signal SIGABRT, Aborted.
0x000000313083304f in raise () from /lib/libc.so.6
(gdb) bt full
#0  0x000000313083304f in raise () from /lib/libc.so.6
No symbol table info available.
#1  0x000000313083447a in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x000000313288f66d in __gnu_cxx::__verbose_terminate_handler() () from /lib/libstdc++.so.6
No symbol table info available.
#3  0x000000313288d646 in ?? () from /lib/libstdc++.so.6
No symbol table info available.
#4  0x000000313288d691 in std::terminate() () from /lib/libstdc++.so.6
No symbol table info available.
#5  0x000000313288d8a8 in __cxa_throw () from /lib/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7c8a7b4 in PoDoFo::PdfOutputDevice::PdfOutputDevice(char const*, bool) ()
   from /app/lib/libpodofo.so.0.9.6-rc1
No symbol table info available.
#7  0x00007ffff7d160fd in PoDoFo::PdfMemDocument::Write(char const*) ()
   from /app/lib/libpodofo.so.0.9.6-rc1
No symbol table info available.
#8  0x0000000000434635 in PoDoFoOutputPdfFile::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
No symbol table info available.
#9  0x00000000004265ca in MainWindow::generate_pdf() ()
No symbol table info available.
#10 0x000000000042739c in MainWindow::generate_pdf_button_pressed() ()
No symbol table info available.
#11 0x00007ffff6c17855 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib/libQt5Core.so.5
No symbol table info available.
#12 0x00007ffff6c17c1d in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
```

**Comment by marcoscarpetta** [comment] 2018-07-01 18:54
It's working for me on Arch Linux with a system-wide installation. Could you try merging this 2 PDFs [0-1] placed in your home directory?

[0] https://www.gnu.org/software/parted/manual/parted.pdf
[1] https://www.gnu.org/software/bash/manual/bash.pdf

**Comment by Alexander-Wilms** [comment] 2018-07-07 16:17
Sorry for the delay. I can no longer reproducte the issue, neither with the two files you mentioned, nor with any other files.

**Comment by marcoscarpetta** [comment] 2018-07-09 07:29
Ok, thank you. I'm closing this issue, since the problem is related to the application itself and not the flatpak package. Please report the issue [here](https://gitlab.com/scarpetta/pdfmixtool/issues) if you find other files that crash the application.

**Closed by marcoscarpetta** 2018-07-09 07:29 UTC

**Comment by nedrichards** [comment] 2018-07-09 11:10
@marcoscarpetta would you like us to disable issues for this project? We can do that if you put a README telling people that they should report in your other repo.

**Comment by marcoscarpetta** [comment] 2018-07-09 14:16
I think issues could remain enabled for problems about Flatpak packaging, since the manifest file is inside this repository. The issue reporting URL is specified inside the application and on the application's web page so I think people should already go there for application-specific issues.
